[19/Jan/2022 08:36:51] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[19/Jan/2022 08:36:51] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[19/Jan/2022 08:37:15] INFO [django.server:157] "GET / HTTP/1.1" 200 13852
[19/Jan/2022 08:37:15] INFO [django.server:157] "GET / HTTP/1.1" 200 13852
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/styles.css HTTP/1.1" 200 14220
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/styles.css HTTP/1.1" 200 14220
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/WelcomeIllustration.svg HTTP/1.1" 200 16662
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/WelcomeIllustration.svg HTTP/1.1" 200 16662
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/control.png HTTP/1.1" 200 4946
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/control.png HTTP/1.1" 200 4946
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/save.png HTTP/1.1" 200 5850
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/save.png HTTP/1.1" 200 5850
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/control.svg HTTP/1.1" 200 3985
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/control.svg HTTP/1.1" 200 3985
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/save.svg HTTP/1.1" 200 4815
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/save.svg HTTP/1.1" 200 4815
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/forget.png HTTP/1.1" 200 6121
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/know.png HTTP/1.1" 200 5775
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/know.png HTTP/1.1" 200 5775
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/forget.svg HTTP/1.1" 200 8904
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/know.svg HTTP/1.1" 200 8645
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/know.svg HTTP/1.1" 200 8645
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/X_gray.svg HTTP/1.1" 200 461
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/forget.svg HTTP/1.1" 200 8904
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/forget.png HTTP/1.1" 200 6121
[19/Jan/2022 08:37:16] INFO [django.server:157] "GET /static/application/images/X_gray.svg HTTP/1.1" 200 461
[19/Jan/2022 08:37:16] WARNING [django.request:224] Not Found: /favicon.ico
[19/Jan/2022 08:37:16] WARNING [django.request:224] Not Found: /favicon.ico
[19/Jan/2022 08:37:16] WARNING [django.server:157] "GET /favicon.ico HTTP/1.1" 404 2878
[19/Jan/2022 08:37:16] WARNING [django.server:157] "GET /favicon.ico HTTP/1.1" 404 2878
[19/Jan/2022 08:37:38] WARNING [django.request:224] Not Found: /application/layout
[19/Jan/2022 08:37:38] WARNING [django.request:224] Not Found: /application/layout
[19/Jan/2022 08:37:38] WARNING [django.server:157] "GET /application/layout HTTP/1.1" 404 7586
[19/Jan/2022 08:37:38] WARNING [django.server:157] "GET /application/layout HTTP/1.1" 404 7586
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /application/callUs HTTP/1.1" 200 2900
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /application/callUs HTTP/1.1" 200 2900
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 200 17555
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 200 17555
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 200 801
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 200 801
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/X_white.svg HTTP/1.1" 200 2018
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/X_white.svg HTTP/1.1" 200 2018
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 200 798
[19/Jan/2022 08:37:44] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 200 798
[19/Jan/2022 08:38:23] INFO [django.server:157] "GET /dashboard/notifyRemaining HTTP/1.1" 200 2287
[19/Jan/2022 08:38:23] INFO [django.server:157] "GET /dashboard/notifyRemaining HTTP/1.1" 200 2287
[19/Jan/2022 08:38:23] INFO [django.server:157] "GET /static/dashboard/styles_app.css HTTP/1.1" 200 16043
[19/Jan/2022 08:38:23] INFO [django.server:157] "GET /static/dashboard/styles_app.css HTTP/1.1" 200 16043
[19/Jan/2022 08:38:34] ERROR [django.request:224] Internal Server Error: /dashboard/files
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\dashboard\views.py", line 42, in files
    if request.user.programs.snap == False and request.user.programs.freeReducedLunch == False:
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\utils\functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'programs'
[19/Jan/2022 08:38:34] ERROR [django.request:224] Internal Server Error: /dashboard/files
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\dashboard\views.py", line 42, in files
    if request.user.programs.snap == False and request.user.programs.freeReducedLunch == False:
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\utils\functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'programs'
[19/Jan/2022 08:38:34] ERROR [django.request:224] Internal Server Error: /dashboard/filesContinued
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\dashboard\views.py", line 185, in filesContinued
    "Utility Bill": request.user.addressverification.Utility,
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\utils\functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'addressverification'
[19/Jan/2022 08:38:34] ERROR [django.request:224] Internal Server Error: /dashboard/filesContinued
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\dashboard\views.py", line 185, in filesContinued
    "Utility Bill": request.user.addressverification.Utility,
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\utils\functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'addressverification'
[19/Jan/2022 08:38:34] ERROR [django.server:157] "GET /dashboard/files HTTP/1.1" 500 73598
[19/Jan/2022 08:38:34] ERROR [django.server:157] "GET /dashboard/filesContinued HTTP/1.1" 500 73472
[19/Jan/2022 08:38:34] ERROR [django.server:157] "GET /dashboard/filesContinued HTTP/1.1" 500 73472
[19/Jan/2022 08:38:34] ERROR [django.server:157] "GET /dashboard/files HTTP/1.1" 500 73598
[19/Jan/2022 08:38:38] INFO [django.server:157] "GET /dashboard/FAQ HTTP/1.1" 200 13641
[19/Jan/2022 08:38:38] INFO [django.server:157] "GET /dashboard/FAQ HTTP/1.1" 200 13641
[19/Jan/2022 08:38:38] INFO [django.server:157] "GET /static/dashboard/styles.css HTTP/1.1" 200 22191
[19/Jan/2022 08:38:38] INFO [django.server:157] "GET /static/dashboard/styles.css HTTP/1.1" 200 22191
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/LogOut.svg HTTP/1.1" 200 289
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Dashboard.svg HTTP/1.1" 200 199
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Dashboard.svg HTTP/1.1" 200 199
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/AlertBell.svg HTTP/1.1" 200 864
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/AlertBell.svg HTTP/1.1" 200 864
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/ProgramList.svg HTTP/1.1" 200 2128
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/ProgramList.svg HTTP/1.1" 200 2128
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/LogOut.svg HTTP/1.1" 200 289
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Settings.svg HTTP/1.1" 200 1654
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Settings.svg HTTP/1.1" 200 1654
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/PrivacyPolicy.svg HTTP/1.1" 200 1468
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/PrivacyPolicy.svg HTTP/1.1" 200 1468
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Path%201083.svg HTTP/1.1" 200 228
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/Path%201083.svg HTTP/1.1" 200 228
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/reviewStarUnfilled.svg HTTP/1.1" 200 1178
[19/Jan/2022 08:38:39] INFO [django.server:157] "GET /static/dashboard/images/reviewStarUnfilled.svg HTTP/1.1" 200 1178
[19/Jan/2022 08:41:30] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py changed, reloading.
[19/Jan/2022 08:41:30] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetYourConnexion\DigitalEquity_MobileVers\mobileVers\application\views.py changed, reloading.
